name: dehancer_slider
description: Dehancer Slider package
version: 1.0.0+1
homepage: https://github.com/dehancer/dehancer-slider

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1
