name: dehancer_slider
description: Flutter package that provides configurable and easy to use slider UI value picker.
version: 1.0.3
homepage: https://www.dehancer.com
repository: https://github.com/dehancer/dehancer-slider

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1
